In [ ]:
import pandas as pd
import numpy as np

In [3]:
# load the data
data = pd.read_csv('/content/Final_Project_dataset.csv')
data.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases,Unnamed: 19,Unnamed: 20
0,1,55,Male,Blouse,Clothing,$53.00,Kentucky,L,Gray,Winter,...,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly,NaN,NaN
1,2,19,Male,Sweater,Clothing,$64.00,Maine,L,Maroon,Winter,...,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly,NaN,NaN
2,3,50,Male,Jeans,Clothing,$73.00,Massachusetts,S,Maroon,Spring,...,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly,NaN,NaN
3,4,21,Male,Sandals,Footwear,$90.00,Rhode Island,M,Maroon,Spring,...,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly,NaN,NaN
4,5,45,Male,Blouse,Clothing,$49.00,Oregon,M,Turquoise,Spring,...,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually,NaN,NaN

In [4]:
print('number of rows and columns', data.shape)
print('Columns Name: ', list(data.columns))

number of rows and columns (3900, 21)
Columns Name:  ['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category', 'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season', 'Review Rating', 'Subscription Status', 'Payment Method', 'Shipping Type', 'Discount Applied', 'Promo Code Used', 'Previous Purchases', 'Preferred Payment Method', 'Frequency of Purchases', 'Unnamed: 19', 'Unnamed: 20']

In [5]:
# show the data types of each column
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer ID               3900 non-null   int64
 1   Age                       3900 non-null   int64
 2   Gender                    3900 non-null   object
 3   Item Purchased            3900 non-null   object
 4   Category                  3900 non-null   object
 5   Purchase Amount (USD)     3900 non-null   object
 6   Location                  3900 non-null   object
 7   Size                      3900 non-null   object
 8   Color                     3900 non-null   object
 9   Season                    3900 non-null   object
 10  Review Rating             3900 non-null   float64
 11  Subscription Status       3900 non-null   object
 12  Payment Method            3900 non-null   object
 13  Shipping Type             3900 non-null   object
 14  Discount Applied          3900 non-null   object
 15  Promo Code Used           3900 non-null   object
 16  Previous Purchases        3900 non-null   int64
 17  Preferred Payment Method  3900 non-null   object
 18  Frequency of Purchases    3900 non-null   object
 19  Unnamed: 19               0 non-null      float64
 20  Unnamed: 20               0 non-null      float64
dtypes: float64(3), int64(3), object(15)
memory usage: 640.0+ KB

In [6]:
# show the summary statistics of the dataset
data.describe()

,Customer ID,Age,Review Rating,Previous Purchases,Unnamed: 19,Unnamed: 20
count,3900.000000,3900.000000,3900.000000,3900.000000,0.0,0.0
mean,1950.500000,44.068462,3.749949,25.351538,NaN,NaN
std,1125.977353,15.207589,0.716223,14.447125,NaN,NaN
min,1.000000,18.000000,2.500000,1.000000,NaN,NaN
25%,975.750000,31.000000,3.100000,13.000000,NaN,NaN
50%,1950.500000,44.000000,3.700000,25.000000,NaN,NaN
75%,2925.250000,57.000000,4.400000,38.000000,NaN,NaN
max,3900.000000,70.000000,5.000000,50.000000,NaN,NaN

**Data Quality**

In [7]:
#check for missing values
data.isnull().sum()

Customer ID                    0
Age                            0
Gender                         0
Item Purchased                 0
Category                       0
Purchase Amount (USD)          0
Location                       0
Size                           0
Color                          0
Season                         0
Review Rating                  0
Subscription Status            0
Payment Method                 0
Shipping Type                  0
Discount Applied               0
Promo Code Used                0
Previous Purchases             0
Preferred Payment Method       0
Frequency of Purchases         0
Unnamed: 19                 3900
Unnamed: 20                 3900
dtype: int64

In [8]:
# check for Unnmamed columns
print(data[['Unnamed: 19', 'Unnamed: 20']].head(10).to_string())

   Unnamed: 19  Unnamed: 20
0          NaN          NaN
1          NaN          NaN
2          NaN          NaN
3          NaN          NaN
4          NaN          NaN
5          NaN          NaN
6          NaN          NaN
7          NaN          NaN
8          NaN          NaN
9          NaN          NaN

In [9]:
# drop the Unnamed columns
data = data.drop(columns = ['Unnamed: 19', 'Unnamed: 20'])

In [10]:
print('Data Duplicates:',data.duplicated().sum())
print('Data Types:',data.dtypes)

Data Duplicates: 0
Data Types: Customer ID                   int64
Age                           int64
Gender                       object
Item Purchased               object
Category                     object
Purchase Amount (USD)        object
Location                     object
Size                         object
Color                        object
Season                       object
Review Rating               float64
Subscription Status          object
Payment Method               object
Shipping Type                object
Discount Applied             object
Promo Code Used              object
Previous Purchases            int64
Preferred Payment Method     object
Frequency of Purchases       object
dtype: object

In [11]:
data['Purchase Amount (USD)'] = (data['Purchase Amount (USD)'].astype(str).str.replace('$', ''))
data['Purchase Amount (USD)'] = pd.to_numeric(data['Purchase Amount (USD)'])

In [12]:
# check the data type of the 'Purchase Amount (USD)' column
(data['Purchase Amount (USD)'].dtype)

dtype('float64')

The dataset contained 3900 rows and 21 columns.


1.   Missing Values: Two unnamed columns containg missing values and were removerd after checking their contents. the remaining columns had no missing values.
2.   Data types: The Purchase Amount column was stored as a string because the values contained $. I removed the dollar signs and convered the column to a numeric data type(Float)
3. Duplicated Records: I Found no duplicates.

**Descriptive Statistics**

In [13]:
col_num = ['Age', 'Purchase Amount (USD)', 'Review Rating', 'Previous Purchases']

for col in col_num:
    print(f' Number {col}: {data[col].count()}')
    print(f' Sum {col}: {data[col].sum()}')
    print(f' Mean {col}: {data[col].mean().round(2)}')
    print(f' Min {col}: {data[col].min()}')
    print(f' Max {col}: {data[col].max()}')
    print()

 Number Age: 3900
 Sum Age: 171867
 Mean Age: 44.07
 Min Age: 18
 Max Age: 70

 Number Purchase Amount (USD): 3900
 Sum Purchase Amount (USD): 233081.0
 Mean Purchase Amount (USD): 59.76
 Min Purchase Amount (USD): 20.0
 Max Purchase Amount (USD): 100.0

 Number Review Rating: 3900
 Sum Review Rating: 14624.8
 Mean Review Rating: 3.75
 Min Review Rating: 2.5
 Max Review Rating: 5.0

 Number Previous Purchases: 3900
 Sum Previous Purchases: 98871
 Mean Previous Purchases: 25.35
 Min Previous Purchases: 1
 Max Previous Purchases: 50


**Key-findings**



*   The dataset contain 3,900 records. the average customer age is 44.07 years, with age ranging from 18 to 70 years.
*   The total purchase amount is 233081$, and average is 59.76
*   The average view rating is 3.75 out of 5. indicate the average rating is above the midpoint of the scale.
*   The average number of previous purchases is 25.35 with values raning from 1 to 50.

**Exploratory Analysis**

In [14]:
col_cat = ['Gender', 'Item Purchased' ,'Category', 'Location','Size','Color','Season','Payment Method', 'Shipping Type', 'Preferred Payment Method']

for col in col_cat:
    print(data[col].value_counts())
    print()

Gender
Male      2652
Female    1248
Name: count, dtype: int64

Item Purchased
Blouse        171
Pants         171
Jewelry       171
Shirt         169
Dress         166
Sweater       164
Jacket        163
Coat          161
Sunglasses    161
Belt          161
Sandals       160
Socks         159
Skirt         158
Scarf         157
Shorts        157
Hat           154
Handbag       153
Hoodie        151
Shoes         150
T-shirt       147
Sneakers      145
Boots         144
Backpack      143
Gloves        140
Jeans         124
Name: count, dtype: int64

Category
Clothing       1737
Accessories    1240
Footwear        599
Outerwear       324
Name: count, dtype: int64

Location
Montana           96
California        95
Idaho             93
Illinois          92
Alabama           89
Minnesota         88
New York          87
Nevada            87
Nebraska          87
Delaware          86
Maryland          86
Vermont           85
Louisiana         84
North Dakota      83
West Virginia     81
Missouri          81
New Mexico        81
Mississippi       80
Kentucky          79
Arkansas          79
Georgia           79
Indiana           79
Connecticut       78
North Carolina    78
Maine             77
Ohio              77
Virginia          77
Texas             77
Tennessee         77
South Carolina    76
Oklahoma          75
Wisconsin         75
Colorado          75
Oregon            74
Pennsylvania      74
Michigan          73
Washington        73
Alaska            72
Massachusetts     72
Utah              71
Wyoming           71
New Hampshire     71
South Dakota      70
Iowa              69
Florida           68
New Jersey        67
Arizona           65
Hawaii            65
Rhode Island      63
Kansas            63
Name: count, dtype: int64

Size
M     1755
L     1053
S      663
XL     429
Name: count, dtype: int64

Color
Olive        177
Yellow       174
Silver       173
Teal         172
Green        169
Black        167
Cyan         166
Violet       166
Gray         159
Maroon       158
Orange       154
Charcoal     153
Pink         153
Blue         152
Magenta      152
Purple       151
Peach        149
Red          148
Beige        147
Indigo       147
Lavender     147
Turquoise    145
White        142
Brown        141
Gold         138
Name: count, dtype: int64

Season
Spring    999
Fall      975
Winter    971
Summer    955
Name: count, dtype: int64

Payment Method
Credit Card      696
Venmo            653
Cash             648
PayPal           638
Debit Card       633
Bank Transfer    632
Name: count, dtype: int64

Shipping Type
Free Shipping     675
Standard          654
Store Pickup      650
Next Day Air      648
Express           646
2-Day Shipping    627
Name: count, dtype: int64

Preferred Payment Method
PayPal           677
Credit Card      671
Cash             670
Debit Card       636
Venmo            634
Bank Transfer    612
Name: count, dtype: int64

In [15]:
(data['Discount Applied'] == data['Promo Code Used']).all()

np.True_

In [16]:
Category_sales = data.groupby('Category')['Purchase Amount (USD)'].sum().sort_values(ascending=False)
Category_sales

Category
Clothing       104264.0
Accessories     74200.0
Footwear        36093.0
Outerwear       18524.0
Name: Purchase Amount (USD), dtype: float64

In [17]:
clothing = data[data['Category'] == 'Clothing']
clothing_sales = clothing.groupby('Item Purchased')['Purchase Amount (USD)'].sum().sort_values(ascending=False)
clothing_sales

Item Purchased
Blouse     10410.0
Shirt      10332.0
Dress      10320.0
Pants      10090.0
Sweater     9462.0
Shorts      9433.0
Skirt       9402.0
Socks       9252.0
T-shirt     9248.0
Hoodie      8767.0
Jeans       7548.0
Name: Purchase Amount (USD), dtype: float64

In [18]:
Blouse = clothing[clothing['Item Purchased'] == 'Blouse']
Blouse_size = Blouse.groupby('Size')['Purchase Amount (USD)'].sum().sort_values(ascending=False)
Blouse_size

Size
M     4466.0
L     2655.0
S     1962.0
XL    1327.0
Name: Purchase Amount (USD), dtype: float64

In [19]:
Blouse['Size'].value_counts()

Size
M     75
L     46
S     29
XL    21
Name: count, dtype: int64

In [20]:
clothing['Size'].value_counts()

Size
M     778
L     481
S     284
XL    194
Name: count, dtype: int64

Insight1: Clothing & Blouses Analysis
Clothing achieved the highest total sales among all categories, generating 104,264$.

Within the clothing category, Blouse recored the highest total sales at 10,410$
Futher Analysis showed that size M generated the highest Blouse sales 4466$ and had  the highest number of purchases 75, followed by size L with 2,655$ sales and 46 purchase.

In [21]:
clothing_season = clothing.groupby('Season')['Purchase Amount (USD)'].sum().sort_values(ascending=False)
clothing_season.head(5)

Season
Spring    27692.0
Winter    27274.0
Fall      26220.0
Summer    23078.0
Name: Purchase Amount (USD), dtype: float64

In [22]:
blouse_season = Blouse.groupby('Season')['Purchase Amount (USD)'].sum().sort_values(ascending=False)
blouse_season

Season
Spring    2771.0
Fall      2690.0
Summer    2616.0
Winter    2333.0
Name: Purchase Amount (USD), dtype: float64

In [23]:
pd.crosstab(Blouse['Season'], Blouse['Item Purchased'])

Item Purchased  Blouse
Season
Fall                42
Spring              46
Summer              43
Winter              40

Insigh2: Spring performed best for both total clothing sales and Blouse sales in this dataset.
The business could investigate seasonal demand and plan inventory accordingly

In [24]:
clothing['Discount Applied'].value_counts()

Discount Applied
No     1006
Yes     731
Name: count, dtype: int64

In [25]:
clothing.groupby('Discount Applied')['Purchase Amount (USD)'].agg(['count', 'sum', 'mean']).round(2)

                  count      sum   mean
Discount Applied
No                 1006  60585.0  60.22
Yes                 731  43679.0  59.75

In [26]:
pd.crosstab(clothing['Gender'], clothing['Discount Applied'])

Discount Applied   No  Yes
Gender
Female            556    0
Male              450  731

In [27]:
pd.crosstab([data['Gender'], data['Category']], [data['Discount Applied']])

Discount Applied     No  Yes
Gender Category
Female Accessories  392    0
       Clothing     556    0
       Footwear     199    0
       Outerwear    101    0
Male   Accessories  305  543
       Clothing     450  731
       Footwear     141  259
       Outerwear     79  144

In [28]:
pd.crosstab(clothing['Season'], clothing['Discount Applied'])

Discount Applied   No  Yes
Season
Fall              275  152
Spring            250  204
Summer            224  184
Winter            257  191

Insight3: Discount Distribution by Gender
Discount usage differs between female and male customer across all product categories.

Across all categories, female customer had 1248 records with no discounts and 0 with discounts,
While male customer had 975 without discounts ND 1,677 with discounts.

In [29]:
clothing_Location = data.groupby('Location')['Purchase Amount (USD)'].count().sort_values(ascending=False)
clothing_Location.head(10)

Location
Montana       96
California    95
Idaho         93
Illinois      92
Alabama       89
Minnesota     88
Nebraska      87
Nevada        87
New York      87
Delaware      86
Name: Purchase Amount (USD), dtype: int64

In [30]:
Location_Previous = data.groupby('Location')['Previous Purchases'].sum().sort_values(ascending=False)
Location_Previous.head(10)

Location
Illinois      2447
Alabama       2443
Montana       2426
California    2327
Minnesota     2307
Maryland      2282
Missouri      2280
Nevada        2265
Idaho         2251
Nebraska      2154
Name: Previous Purchases, dtype: int64